name: Web CI

on:
  workflow_dispatch:
  push:
    paths:
      - "."
      - ".github/workflows/web-ci.yml"

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node-env
        with:
          node-version: 18
          cache-path: web/node_modules
          cache-key: "${{hashFiles('./package-lock.json')}}"
          project: byte-auction
      - run: npm run build
